# Data import

## Countries ranked by universities (Webometrics)

- Dataset: https://www.webometrics.info/en/distribution_by_country

```{r}
df_ranks <- read.csv('data/webometrics.tsv', sep = '\t')

# Set country rank based on row number
df_ranks$Rank <- 1:nrow(df_ranks)
```

```{r results = TRUE}
kable(head(df_ranks, 10))
```

## University ranks (Shanghai rankings)

- Name: Academic Ranking of World Universities (ARWU) - Shanghai Rankings from 2005-2018
- Dataset: https://www.kaggle.com/datasets/joebeachcapital/shanghai-world-university-ranking

```{r}
library(dplyr)
df_uni <- read.csv('data/shanghai-world-university-ranking.csv',
                   sep = ';',
                   na = "")
# Remove unnecessary columns
df_uni <- df_uni %>% select(-c(Geo.Shape, Geo.Point.2D))

# Rename columns
df_uni <- df_uni %>% rename("Rank" = "World.rank.integer")
```
```{r results = TRUE}
kable(head(df_uni %>% select(c("World.rank", "Rank", "University", "Country")), 10))
```
```{r include = FALSE}
str(df_uni)
```



```{r}
# Validate the total score.
Total_score <- function(df) {
  score <- df$Alumni*0.1 + df$Award*0.2 + df$Hi.Ci*0.2 + df$N.S*0.2 + df$PUB*0.2 + df$PCP*0.1
  return(score)
}

df_uni$Total_score <- Total_score(df_uni)
```
## Human Development Index (HDI)

- Website: https://hdr.undp.org/data-center/human-development-index
- Dataset: https://hdr.undp.org/sites/default/files/2021-22_HDR/HDR21-22_Composite_indices_complete_time_series.csv
- Metadata: https://hdr.undp.org/sites/default/files/2021-22_HDR/HDR21-22_Composite_indices_metadata.xlsx

```{r}
df_hdi <- read.csv('data/HDR21-22_Composite_indices_complete_time_series.csv', sep = ',')

# Select only years which are included in the shanghai uni rankings as well
hdi_years <- 2005:2018

# Select indicators from the HDI group only
df_hdi <- df_hdi %>%
         select(c(iso3, country, hdicode, hdi_rank_2021),
                paste0("hdi_", hdi_years),    # Human Development Index (value)
                paste0("le_", hdi_years),     # Life Expectancy at Birth (years)
                paste0("eys_", hdi_years),    # Expected Years of Schooling (years)
                paste0("mys_", hdi_years),    # Mean Years of Schooling (years)
                paste0("gnipc_", hdi_years),  # Gross National Income Per Capita (2017 PPP$)
         )
```

```{r results = TRUE}
kable(head(df_hdi %>% select(c(iso3, country, hdicode, hdi_rank_2021, hdi_2005, hdi_2018, le_2005, le_2018)), 10))
```
